In [1]:
#Email code to mbroadnax@iq.harvard.edu
import numpy as np

hello = 'Hello, world.'
print( hello )

#one-dimensional array
arr1 = np.array( [1, 2, 3] )
print( arr1 ) 

Hello, world.
[1 2 3]


In [31]:
#two-dimensional array
arr2 = np.array( [ [1,2], [3,4] ] )
print( arr2 )

[[1 2]
 [3 4]]


In [23]:
#specify the number of dimensions
arr3 = np.array( [1, 2, 3, 4, 5, 6], ndmin = 3 )
print( arr3 )

[[[1 2 3 4 5 6]]]


In [12]:
arr_float = np.array( arr3, dtype = float )
print( arr_float )

[[[1. 2. 3. 4. 5. 6.]]]


In [18]:
arr_bool = np.array( [0, 1, 0, 1], dtype = bool )
print( arr_bool )

[False  True False  True]


In [19]:
#get the array dimensions
print( arr3 )
print( arr3.shape )

[[[1 2 3 4 5 6]]]
(1, 1, 6)


In [29]:
#resize an array using the .shape attribute
arr4 = np.array( arr2 )
print( arr4 )
print( arr4.shape, '\n' )

arr4.shape = (4, 1)
print( arr4 )
print( arr4.shape )

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
(2, 2) 

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [57]:
#Need to Fix
#arr5 = arr2.reshape( 4, 1 )
#print( arr5 )

In [36]:
x = np.arange( 1, 20 )
print( x )

y = np.linspace( 1, 20 )
print( y )

xnum = [ 1, 2, 3, 4 ]
xnum_arr = np.asarray( xnum )
print( xnum_arr )

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]
[1, 2, 3, 4]
[1 2 3 4]


In [37]:
#Slicing a 1D Array -> Create a slice using colons [start:stop:step]
a = np.arange( 5, 30, 2 )
print( a )
print( a[:5] )
print( a[2:5] )
print( a[7:] )

#reverses the array
print( a[::-1] )


[ 5  7  9 11 13 15 17 19 21 23 25 27 29]
[ 5  7  9 11 13]
[ 9 11 13]
[19 21 23 25 27 29]
[29 27 25 23 21 19 17 15 13 11  9  7  5]


In [38]:
#Slicing a 2D Array 
b = np.array( [ [1, 2, 3, 4, 5], 
                [2, 4, 6, 8, 10],
                [3, 6, 9, 12, 15],
                [5, 10, 15, 20, 25], 
                [6, 12, 18, 24, 30] ] )
print( b, '\n' )

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 5 10 15 20 25]
 [ 6 12 18 24 30]] 



In [39]:
#Modifying an array element - Arrays have a fixed type, so if you assign a value with a different type, you may end up with unexpected behavior
k = np.array( [ [1, 2, 3, 4], [2, 4, 6, 8], [3, 6, 9, 12] ] ) 

ksub = k[:3, :2]
print( k )
print( ksub ) 

#modify a value
ksub[1, 0] = 100
print( k )
print( ksub )
    

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]]
[[1 2]
 [2 4]
 [3 6]]
[[  1   2   3   4]
 [100   4   6   8]
 [  3   6   9  12]]
[[  1   2]
 [100   4]
 [  3   6]]


In [41]:
#Combining Arrays
m = np.array( [9, 18, 27, 36] )
n = np.array( [10, 20,30, 40] )
o = np.array( [7, 14, 21, 28] )

print( np.concatenate( [m,n] ) )
print( np.concatenate( [m,n,o] ) )

print(np.vstack( [m,n,o] ) )
print(np.hstack( [m,n,o] ) )

[ 9 18 27 36 10 20 30 40]
[ 9 18 27 36 10 20 30 40  7 14 21 28]
[[ 9 18 27 36]
 [10 20 30 40]
 [ 7 14 21 28]]
[ 9 18 27 36 10 20 30 40  7 14 21 28]


In [42]:
#Numpy Mathmatical Operations
r = np.arange( 8 )
print( "r =", r )
print( "r + 10 =", r + 10 )
print( "r / 2 =", r / 2 )

r = [0 1 2 3 4 5 6 7]
r + 10 = [10 11 12 13 14 15 16 17]
r / 2 = [0.  0.5 1.  1.5 2.  2.5 3.  3.5]


In [46]:
s = np.arange( 100 )

def div_by_2( array ):
    v = np.empty( len( array ) )
    for i in range( len( array ) ):
        v[i] = i / 2
    return v

r2 = div_by_2( r )
#print( r2 )

%timeit s2_numpy = s / 2
print( len( s2_numpy ) )

%timeit s2_loop = div_by_2( s )
print( len( s2_loop ) )


1.32 µs ± 16.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
100
8.97 µs ± 74.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
100


In [48]:
#Summary Statistics
X = np.random.random( 1000 )
print( np.sum( X ) )
x_range = ( X.min( ), X.max( ) )
print( x_range )

Y = np.random.random( ( 3, 4 ) ) 
print( Y, '\n' )

print( Y.sum( axis = 0 ) ) #columns
print( Y.sum( axis = 1 ) ) #axis is the dimension to collapse

499.969718279826
(0.0005134403467200732, 0.9977800027147741)
[[0.85527627 0.33391885 0.21618135 0.75981813]
 [0.59812825 0.75251153 0.46261861 0.55677371]
 [0.10679275 0.22080519 0.81500449 0.61958448]] 

[1.56019727 1.30723557 1.49380446 1.93617632]
[2.1651946  2.3700321  1.76218691]


In [56]:
num_values = 100 
array = np.random.randint( 1, 10, num_values, dtype = int )
print( array )

print( " mean =", np.mean( array ) )
print( " variance =", np.var( array ) )
print( " standard deviation =", np.std( array ) )
print( " median =", np.median( array ) )

[2 8 2 7 4 4 1 7 7 5 9 5 1 3 1 4 6 4 3 9 1 6 9 8 7 2 2 7 3 4 3 1 4 5 2 8 1
 3 5 1 9 9 6 4 1 5 3 3 3 7 9 9 5 8 1 9 7 3 2 1 5 7 6 5 6 2 6 3 4 9 2 4 5 1
 6 9 3 3 8 7 9 2 8 8 5 5 5 6 9 8 4 3 2 2 2 4 6 6 5 5]
 mean = 4.83
 variance = 6.541100000000001
 standard deviation = 2.5575574284852336
 median = 5.0
